# Generated by Django 5.2 on 2026-04-14 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticeread',
            old_name='faculty',
            new_name='user',
        ),
        migrations.AddField(
            model_name='notice',
            name='target_section',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_year',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='recipient_type',
            field=models.CharField(choices=[('all_faculty', 'All Faculty'), ('specific_faculty', 'Specific Faculty'), ('all_students', 'All Students'), ('specific_students', 'Specific Students')], default='all_faculty', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='noticeread',
            unique_together={('notice', 'user')},
        ),
    ]
