# Generated by Django 5.2 on 2026-03-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyprofile',
            name='hod_year_group',
            field=models.CharField(blank=True, choices=[('1', '1st Year (Sem 1-2)'), ('2', '2nd Year (Sem 3-4)'), ('3', '3rd Year (Sem 5-6)'), ('4', '4th Year (Sem 7-8)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
    ]
