# Generated by Django 5.2 on 2026-04-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_facultyprofile_hod_year_group_facultyprofile_is_hod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyprofile',
            name='hod_year_group',
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='hod_year_1',
            field=models.BooleanField(default=False, verbose_name='HOD of 1st Year (Sem 1-2)'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='hod_year_2',
            field=models.BooleanField(default=False, verbose_name='HOD of 2nd Year (Sem 3-4)'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='hod_year_3',
            field=models.BooleanField(default=False, verbose_name='HOD of 3rd Year (Sem 5-6)'),
        ),
        migrations.AddField(
            model_name='facultyprofile',
            name='hod_year_4',
            field=models.BooleanField(default=False, verbose_name='HOD of 4th Year (Sem 7-8)'),
        ),
    ]
